### ISSUE TITLE
Module build failed: Error: ENOENT: no such file or directory, open 'D:\localhost\test\D:\localhost\test\styles.scss'

### ISSUE THREAD

**Issue by bencergazda** [jgranstrom/sass-extract#10]
I get the following error on Windows, which is just started to happen after upgrading to 0.5.0.

	Hash: 98d8a632299bd19989c3
	Version: webpack 3.3.0
	Time: 222ms
		   Asset     Size  Chunks             Chunk Names
	dist/test.js  3.69 kB       0  [emitted]  test.js
	   [0] ./test.js 569 bytes {0} [built]
	   [1] ./node_modules/sass-extract-loader!./styles.scss 166 bytes {0} [built] [failed] [1 error]

	ERROR in ./node_modules/sass-extract-loader!./styles.scss
	Module build failed: Error: ENOENT: no such file or directory, open 'D:\localhost\test\D:\localhost\test\styles.scss'
	  at Error (native)

	 @ ./test.js 15:0-65

It looks like it appends one path to another: *D:\localhost\test\D:\localhost\test\styles.scss*. It is a custom test environment, but the examples in sass-extract-loader also fail now on Windows:

	ERROR in ./~/sass-extract-loader!./src/gradient-rectangle/gradient-rectangle.scss
	Module build failed: Error: ENOENT: no such file or directory, open 'D:\Downloads\sass-extract-loader-master2\examples\visual\D:\Downloads\sass-extract-loader-master2\examples\visual\src\gradient-rectangle\gradient-rectangle.scss'
		at Error (native)
	 @ ./src/gradient-rectangle/gradient-rectangle.js 4:12-68
	 @ ./src/index.js
	 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./index.js

If I revert the changes from https://github.com/jgranstrom/sass-extract/commit/f2bc8b1ab6423ae6e2cb600800b02d660982badb#diff-19b7dd157933fc27ee38258cb120e62f, it works.

**Comment by jgranstrom** [comment]
@bencergazda There was a windows compatibility issue introduced in that release due to the lack of automated testing on Windows specifically. There is a new patch out `0.5.2` that includes a fix for this. I have also added automated testing on the Windows platform at [AppVeyor](https://ci.appveyor.com/project/jgranstrom/sass-extract) in addition to the existing TravisCI integration to make sure it is tested for each release.

`npm install sass-extract@0.5.2` and you should be good to go.

**Comment by bencergazda** [comment]
Now works as expected, thanks!
