### ISSUE TITLE
Compact should not drop unit / new plugin needed

### ISSUE THREAD

**Issue by jrencz** [jgranstrom/sass-extract#26]
I recently added the `compact` plugin to my build process incorporating `sass-extract` via `sass-extract-loader` and I was quite happy about it until I found out that if original value is e.g. `8px` then what I get with `compact` enabled is just `8` (number).

Main cause I started using `compact` is the fact it drops the source paths, which I was particularly interested in. 

It's impossible to distinguish `8px` from `8em` with `compact` - it removes too much.

I suggest either `compact` should preserve unit for what it now considers a primitive or there should be a new plugin bundled, which works like `compact` form colors and maps but instead of numbers, it returns strings (with unit) for primitives

**Comment by jgranstrom** [comment]
@jrencz yes the compact plugin simply extracts the raw values in order for numbers to become javascript numbers etc. It is a pretty simple plugin and I will add a more extensive plugin for transforming the result. I will first add support for providing options to plugins, so that a transform plugin can take options such as `preserveNumberUnits` and other transformation options, instead of having to create a multitude of plugins for all kinds of formats.

For now have a look at this [gist](https://gist.github.com/jgranstrom/cfeb00b81df339c413f39029f2228ec1) which is the compact plugin with a few lines changed in order to preserve number units and return them as strings. You can plug that in instead of the built in compact for now the get the results you're after. I will try to get time to put together the improved transformation plugin in the upcoming couple of weeks.

**Comment by jgranstrom** [comment]
I am closing this in favor for the more general #31. For now this can be achieved by providing a custom plugin that formats the original output in any way you might need.

**Comment by bencergazda** [comment]
@jrencz @jgranstrom Please have a look at [jSass](https://github.com/body-builder/jsass#share-sass-variables-with-js). Especially the bundled [sass-extract plugin](https://github.com/body-builder/jsass/blob/master/src/jSass-extract.js) may help a lot.
